import { Text } from '@chakra-ui/react';
import React from 'react';

const AutoGeneratedBadge = () => {
  return (
    <Text
      color="white"
      bgColor="neutral.800"
      py="4px"
      px="7px"
      rounded="16px"
      flexShrink={0}
    >
      Auto-generated
    </Text>
  );
};

export default AutoGeneratedBadge;
