import { Flex, Heading, VStack } from '@chakra-ui/react';

import { Ticket } from '~/lib/interfaces/ticket.interfaces';
import AutoBadge from './AutoBadge';

interface TicketInfoHeaderProps {
  data: Ticket;
  children?: React.ReactNode;
  isUpdateTicket?: boolean;
}
const TicketInfoHeader = (props: TicketInfoHeaderProps) => {
  const { data, children, isUpdateTicket } = props;
  return (
    <Flex
      bgColor="#B4BFCA4D"
      pt="24px"
      px="24px"
      pb="30px"
      width="full"
      alignItems="flex-start"
      direction="column"
    >
      <VStack width="full" alignItems="start" spacing="5px">
        {(data?.isAutoGenerated || data?.isAutoClosed) && (
          <AutoBadge>
            {data?.isAutoClosed ? 'Auto-Closed' : 'Auto-Generated'}
          </AutoBadge>
        )}
        <Heading
          fontSize={{ base: '24px', lg: isUpdateTicket ? '24px' : '32px' }}
          lineHeight={{
            base: '28.51px',
            lg: isUpdateTicket ? '28.51px' : '38.02px',
          }}
          color="black"
          fontWeight={{ base: 700, lg: isUpdateTicket ? 700 : 800 }}
        >
          #{data?.ticketId} {data?.ticketTitle}
        </Heading>
      </VStack>
      {children}
    </Flex>
  );
};

export default TicketInfoHeader;
