import { ApprovalWorkflowPartyInstance } from '~/lib/interfaces/approvalWorkflow.interfaces';
import { ApprovalFlowElement, CustomEdge, CustomNode } from './Interfaces';

const position = { x: 0, y: 0 };

const nodes: CustomNode[] = [
  {
    id: '1',
    data: {
      approveeType: 'individual',
      approveeId: 101,
      approveeName: 'Alice Johnson',
      approveeRole: 'Manager',
      actionStatus: 'completed',
      actionId: 1,
      actionName: 'Budget Approval',
      date: '2025-01-01',
    },
    position,
  },
  {
    id: '2',
    data: {
      approveeType: 'group',
      approveeId: 201,
      approveeGroupName: 'Finance Team',
      actionStatus: 'completed',
      actionId: 2,
      actionName: 'Expense Report Review',
      date: '2025-01-15',
    },
    position,
  },

  {
    id: '4',
    data: {
      approveeType: 'group',
      approveeId: 202,
      approveeGroupName: 'HR Department',
      actionStatus: 'pending',
      actionId: 4,
      actionName: 'Policy Update Review',
      date: '2024-12-20',
    },
    position,
  },
  {
    id: '5',
    data: {
      approveeType: 'group',
      approveeId: 202,
      approveeGroupName: 'HR Department',
      actionStatus: 'completed',
      actionId: 4,
      actionName: 'Policy Update Review',
      date: '2024-12-20',
    },
    position,
  },
  {
    id: '6',
    data: {
      approveeType: 'group',
      approveeId: 202,
      approveeGroupName: 'HR Department',
      actionStatus: 'pending',
      actionId: 4,
      actionName: 'Policy Update Review',
      date: '2024-12-20',
    },
    position,
  },
  {
    id: '7',
    data: {
      approveeType: 'group',
      approveeId: 202,
      approveeGroupName: 'HR Department',
      actionStatus: 'not-started',
      actionId: 4,
      actionName: 'Policy Update Review',
      date: '2024-12-20',
    },
    position,
  },
];

const edges: CustomEdge[] = [
  {
    id: 'e1-2',
    source: '1',
    target: '2',
  },

  {
    id: 'e2-3',
    source: '1',
    target: '4',
  },
  {
    id: 'e3-4df',
    source: '2',
    target: '5',
  },

  {
    id: 'e3-4sd',
    source: '4',
    target: '5',
  },
  {
    id: 'e3-487',
    source: '5',
    target: '6',
  },
  {
    id: 'e3-44587',
    source: '6',
    target: '7',
  },
];

export const initialElements: ApprovalFlowElement[] = [...nodes, ...edges];

export const dummyApprovalPartyInstances: ApprovalWorkflowPartyInstance[] = [
  {
    rowId: 1,
    approvalWorkFlowPartyInstanceId: 1,
    guid: 'a1b2c3d4-e5f6-7890-abcd-1234567890ef',
    parentId: 1,
    levelNumber: 1,
    isDeleted: false,
    approvalWorkFlowInstanceId: 1,
    approvalWorkFlowinstanceName: 'Test Update Approval Workflow',
    approvalActionId: 1,
    requiredAction: 'Require To Approve',
    userId: 31,
    firstName: 'Alice',
    lastName: 'Brown',
    phoneNumber: null,
    email: 'alice.brown@example.com',
    selectedApprovalOptionId: null,
    selectedApprovalOptionName: null,
    currentStatusId: 1,
    currentStatusName: 'Not Started',
    approvalRequestId: 5,
    approvalRequirementTypeId: 1,
    approvalRequirementTypeName: 'Must Approve',
    employeeDesignation: 'Manager',
  },
  {
    rowId: 2,
    approvalWorkFlowPartyInstanceId: 2,
    guid: '02ff74fd-f702-4977-90bd-b2e2aec2e806',
    parentId: 1,
    levelNumber: 2,
    isDeleted: false,
    approvalWorkFlowInstanceId: 1,
    approvalWorkFlowinstanceName: 'Test Update Approval Workflow',
    approvalActionId: 2,
    requiredAction: 'Require To Approve',
    userId: 29,
    firstName: 'Frank',
    lastName: 'Moore',
    phoneNumber: null,
    email: 'fmoorer@example.com',
    selectedApprovalOptionId: null,
    selectedApprovalOptionName: null,
    currentStatusId: 1,
    currentStatusName: 'Not Started',
    approvalRequestId: 5,
    approvalRequirementTypeId: 2,
    approvalRequirementTypeName: 'May Approve',
    employeeDesignation: 'Supervisor',
  },
  {
    rowId: 3,
    approvalWorkFlowPartyInstanceId: 3,
    guid: '34e8f1fe-e63d-49da-9c0e-124e9eb3895b',
    parentId: 1,
    levelNumber: 2,
    isDeleted: false,
    approvalWorkFlowInstanceId: 1,
    approvalWorkFlowinstanceName: 'Test Update Approval Workflow',
    approvalActionId: 3,
    requiredAction: 'Inform When Approved',
    userId: 27,
    firstName: 'David',
    lastName: 'Johnson',
    phoneNumber: null,
    email: 'djohnson@example.com',
    selectedApprovalOptionId: null,
    selectedApprovalOptionName: null,
    currentStatusId: 1,
    currentStatusName: 'Not Started',
    approvalRequestId: 5,
    approvalRequirementTypeId: 3,
    approvalRequirementTypeName: 'Must Acknowledge',
    employeeDesignation: 'Team Lead',
  },
  {
    rowId: 4,
    approvalWorkFlowPartyInstanceId: 4,
    guid: '0bfcdabe-caf6-4b41-9fd7-b8114331cfdc',
    parentId: 2,
    levelNumber: 3,
    isDeleted: false,
    approvalWorkFlowInstanceId: 1,
    approvalWorkFlowinstanceName: 'Test Update Approval Workflow',
    approvalActionId: 4,
    requiredAction: 'Requested The Approval',
    userId: 23,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: null,
    email: 'jdoe@example.com',
    selectedApprovalOptionId: null,
    selectedApprovalOptionName: null,
    currentStatusId: 1,
    currentStatusName: 'Not Started',
    approvalRequestId: 5,
    approvalRequirementTypeId: 1,
    approvalRequirementTypeName: '23',
    employeeDesignation: 'Front-End Developer',
  },
  {
    rowId: 5,
    approvalWorkFlowPartyInstanceId: 5,
    guid: 'b765ddfa-8c63-45be-9101-8ad5f3f43e19',
    parentId: 3,
    levelNumber: 4,
    isDeleted: false,
    approvalWorkFlowInstanceId: 1,
    approvalWorkFlowinstanceName: 'Test Update Approval Workflow',
    approvalActionId: 5,
    requiredAction: 'Review and Comment',
    userId: 35,
    firstName: 'Emma',
    lastName: 'Taylor',
    phoneNumber: null,
    email: 'emma.taylor@example.com',
    selectedApprovalOptionId: null,
    selectedApprovalOptionName: null,
    currentStatusId: 1,
    currentStatusName: 'Not Started',
    approvalRequestId: 5,
    approvalRequirementTypeId: 2,
    approvalRequirementTypeName: 'May Approve',
    employeeDesignation: 'QA Engineer',
  },
  {
    rowId: 6,
    approvalWorkFlowPartyInstanceId: 6,
    guid: 'c432f1d2-89ba-4e6c-9bfa-59b3f4de67cd',
    parentId: 4,
    levelNumber: 4,
    isDeleted: false,
    approvalWorkFlowInstanceId: 1,
    approvalWorkFlowinstanceName: 'Test Update Approval Workflow',
    approvalActionId: 6,
    requiredAction: 'Final Approval',
    userId: 40,
    firstName: 'Sophia',
    lastName: 'Wilson',
    phoneNumber: null,
    email: 'sophia.wilson@example.com',
    selectedApprovalOptionId: null,
    selectedApprovalOptionName: null,
    currentStatusId: 1,
    currentStatusName: 'Not Started',
    approvalRequestId: 5,
    approvalRequirementTypeId: 1,
    approvalRequirementTypeName: 'Must Approve',
    employeeDesignation: 'Director',
  },
];