import { HStack, Icon, Text, Tooltip, VStack } from '@chakra-ui/react';
import React from 'react';
import { InfoIcon } from '~/lib/components/CustomIcons';
import Detail from '~/lib/components/UI/ContentDetails/Detail';

const AlertSummary = () => {
  return (
    <VStack spacing="16px" width="full" alignItems="flex-start">
      <Text color="neutral.600" fontWeight={700}>
        Alert Summary
      </Text>
      <VStack spacing="8px" width="full" alignItems="flex-start">
        <Detail
          label="Risk Score:"
          value="85%"
          labelStyle={{ color: 'neutral.700' }}
          valueStyle={{ fontWeight: 800 }}
        />
        <Detail
          label="Predicted Failure Date:"
          value="Sept 12, 2025"
          labelStyle={{ color: 'neutral.700' }}
          valueStyle={{ fontWeight: 800 }}
        />
        <HStack spacing="16px" width="full">
          <Detail
            label="Confidence Level:"
            value="High"
            labelStyle={{ color: 'neutral.700' }}
            valueStyle={{ fontWeight: 800 }}
          />
          <Tooltip
            label="Confidence reflects model accuracy and data completeness."
            placement="top"
            bgColor="black"
            color="white"
            minW="190px"
            rounded="10px"
            padding="6px"
            fontSize="12px"
          >
            <HStack
              width="12px"
              height="12px"
              justifyContent="center"
              flexShrink={0}
            >
              <Icon as={InfoIcon} boxSize="12px" color="blue.500" />
            </HStack>
          </Tooltip>
        </HStack>
        <Detail
          label="Asset Link:"
          value="View Asset Profile"
          labelStyle={{ color: 'neutral.700' }}
          valueStyle={{
            color: 'blue.500',
            onClick: () => {},
            cursor: 'pointer',
          }}
        />
      </VStack>
      <Text
        bgColor="#17A1FA0D"
        border="1px solid #17A1FA80"
        rounded="6px"
        padding="6px"
        color="black"
        lineHeight="150%"
        fontWeight={400}
      >
        This alert was generated by the predictive maintenance engine. The asset
        shows high likelihood of failure within 7 days.
      </Text>
    </VStack>
  );
};

export default AlertSummary;
