interface TicketPerformanceDashboardSummary {
  totalTickets: number;
  openTickets: number;
  overdueTickets: number;
  slaComplianceRate: number;
}

interface TicketClosedByTechnician {
  technician: string;
  withinSla: number;
  breached: number;
}

interface TicketCreationScore {
  manualEntry: number;
  autoGenerated: number;
  manualEntryPercentage: number;
  autoGeneratedPercentage: number;
}

interface TicketByStatus {
  statusName: string;
  value: number;
  percentage: number;
}

interface TicketPerformanceTrends {
  Closed: PerformanceTrend[];
  Created: PerformanceTrend[];
  Overdue: PerformanceTrend[];
}

interface PerformanceTrend {
  day: Date;
  value: number;
}

interface PriorityLevelCount {
  priorityLevel: string;
  completed: number;
  inProgress: number;
  open: number;
}

interface TicketCountByFacility {
  facility: string;
  ticketCount: number;
  avgResolutionTime: number;
  slaCompliance: number;
}

export type {
  TicketPerformanceDashboardSummary,
  TicketByStatus,
  TicketClosedByTechnician,
  TicketCountByFacility,
  TicketCreationScore,
  TicketPerformanceTrends,
  PriorityLevelCount,
  PerformanceTrend,
};
