import { Company } from "~/lib/interfaces/company.interfaces";

export const dummyCompanies: Company[] = [
  {
    isNew: false,
    createdDate: new Date('2024-01-01'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-02-01'),
    lastModifiedBy: 'user123',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    companyId: 1001,
    companyName: 'Tesla Inc.',
    address: '3500 Deer Creek Road, Palo Alto, CA',
    apikey: 'apikey-12345',
    industry: 'Automotive',
    totalAsset: 500000,
    primaryContacts: 'Elon Musk',
    email: 'contact@tesla.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: false,
    createdDate: new Date('2023-06-15'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-01-10'),
    lastModifiedBy: 'user456',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'b2c3d4e5-f6a1-7890-abcd-ef2233445566',
    companyId: 1002,
    companyName: 'Apple Inc.',
    address: 'One Apple Park Way, Cupertino, CA',
    apikey: 'apikey-67890',
    industry: 'Technology',
    totalAsset: 1500000,
    primaryContacts: 'Tim Cook',
    email: 'contact@apple.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: false,
    createdDate: new Date('2022-09-30'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2024-12-25'),
    lastModifiedBy: 'user789',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'c3d4e5f6-a1b2-7890-abcd-ef3344556677',
    companyId: 1003,
    companyName: 'Google LLC',
    address: '1600 Amphitheatre Parkway, Mountain View, CA',
    apikey: 'apikey-54321',
    industry: 'Technology',
    totalAsset: 2000000,
    primaryContacts: 'Sundar Pichai',
    email: 'contact@google.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: false,
    createdDate: new Date('2021-04-20'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-02-14'),
    lastModifiedBy: 'user321',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'd4e5f6a1-b2c3-7890-abcd-ef4455667788',
    companyId: 1004,
    companyName: 'Amazon Inc.',
    address: '410 Terry Ave N, Seattle, WA',
    apikey: 'apikey-11111',
    industry: 'E-commerce',
    totalAsset: 1800000,
    primaryContacts: 'Andy Jassy',
    email: 'contact@amazon.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: true,
    createdDate: new Date('2025-01-10'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-02-10'),
    lastModifiedBy: 'user567',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'e5f6a1b2-c3d4-7890-abcd-ef5566778899',
    companyId: 1005,
    companyName: 'Meta Platforms',
    address: '1 Hacker Way, Menlo Park, CA',
    apikey: 'apikey-22222',
    industry: 'Social Media',
    totalAsset: 1300000,
    primaryContacts: 'Mark Zuckerberg',
    email: 'contact@meta.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: false,
    createdDate: new Date('2023-05-05'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-02-05'),
    lastModifiedBy: 'user890',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'f6a1b2c3-d4e5-7890-abcd-ef6677889900',
    companyId: 1006,
    companyName: 'Netflix Inc.',
    address: '100 Winchester Circle, Los Gatos, CA',
    apikey: 'apikey-33333',
    industry: 'Entertainment',
    totalAsset: 900000,
    primaryContacts: 'Ted Sarandos',
    email: 'contact@netflix.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: false,
    createdDate: new Date('2020-02-29'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-01-01'),
    lastModifiedBy: 'user111',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'a1b2c3d4-e5f6-7890-abcd-ef7788990011',
    companyId: 1007,
    companyName: 'Microsoft Corporation',
    address: 'One Microsoft Way, Redmond, WA',
    apikey: 'apikey-44444',
    industry: 'Technology',
    totalAsset: 2500000,
    primaryContacts: 'Satya Nadella',
    email: 'contact@microsoft.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: false,
    createdDate: new Date('2024-07-19'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-02-17'),
    lastModifiedBy: 'user222',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'b2c3d4e5-f6a1-7890-abcd-ef8899001122',
    companyId: 1008,
    companyName: 'Adobe Systems',
    address: '345 Park Avenue, San Jose, CA',
    apikey: 'apikey-55555',
    industry: 'Software',
    totalAsset: 800000,
    primaryContacts: 'Shantanu Narayen',
    email: 'contact@adobe.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
  {
    isNew: false,
    createdDate: new Date('2021-11-11'),
    createdBy: 'admin',
    lastModifiedDate: new Date('2025-02-10'),
    lastModifiedBy: 'user333',
    isDeleted: false,
    deletedDate: new Date(),
    deletedBy: '',
    guid: 'c3d4e5f6-a1b2-7890-abcd-ef9900112233',
    companyId: 1009,
    companyName: 'Salesforce',
    address: '50 Fremont Street, San Francisco, CA',
    apikey: 'apikey-66666',
    industry: 'CRM',
    totalAsset: 700000,
    primaryContacts: 'Marc Benioff',
    email: 'contact@salesforce.com',
    subscriptionType: 'Pro',
    subscriptionStatus: 'Active',
  },
];
