import { Asset } from '~/lib/interfaces/asset.interfaces';
import { Option } from '~/lib/interfaces/general.interfaces';

const assetData: Asset[] = [
  {
    assetId: 7,
    assetName: 'Laptop',
    assetCode: 'LPT001',
    assetTag: 'TAG001',
    rfidtag: null,
    serialNo: 'SN001',
    description: 'Dell Laptop',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2023-01-15T00:00:00',
    lifeExpectancy: 5,
    locationId: 1,
    assetTypeId: null,
    statusId: 3,
    categoryId: 4,
    currentOwner: 'John Doe',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 1,
    acquisitionDate: '2023-01-15T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 800,
    scrapvalue: 100,
    parentId: null,
    subCategoryId: 20,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:17:22.0633333',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
  {
    assetId: 8,
    assetName: 'Printer',
    assetCode: 'PRT001',
    assetTag: 'TAG002',
    rfidtag: null,
    serialNo: 'SN002',
    description: 'HP Printer',
    weightKg: null,
    lengthCm: null,
    widthCm: null,
    heightCm: null,
    purchaseDate: '2022-12-20T00:00:00',
    lifeExpectancy: 7,
    locationId: 2,
    assetTypeId: 5,
    statusId: 1,
    categoryId: 7,
    currentOwner: 'Jane Smith',
    responsibleFor: null,
    assignedTo: null,
    conditionId: 2,
    acquisitionDate: '2022-12-20T00:00:00',
    dateCreated: '2024-06-25T14:58:28.43',
    initialValue: null,
    resalevalue: 500,
    scrapvalue: 50,
    parentId: null,
    subCategoryId: 35,
    assetLocation: null,
    assetInfoHeader: null,
    assetComponents: null,
    isNew: false,
    createdDate: '2024-06-21T13:18:47.4766667',
    createdBy: null,
    lastModifiedDate: null,
    lastModifiedBy: null,
    isDeleted: false,
    deletedDate: null,
    deletedBy: null,
    guid: null,
  },
];

const categoryData: Option[] = [
  {
    value: 'IT Equipment',
    label: 'IT Equipment',
  },
  {
    value: 'Vehicle',
    label: 'Vehicle',
  },
  {
    value: 'Machinery',
    label: 'Machinery',
  },
  {
    value: 'Heavy Equipment',
    label: 'Heavy Equipment',
  },
  {
    value: 'Outdoor Equipment',
    label: 'Outdoor Equipment',
  },
];

export { assetData, categoryData };
