name: CI-build-and-push-image-to-dockerhub

# Controls when the action will run.
on:
  # Triggers the workflow on the push or pull request events but only for the master branch
  push:
    branches: ['master']
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: ['master']
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore

  # Allows for this workflow to be executed manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v6.6.0
        with:
          context: .
          file: ./apps/client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/invent3pro-ui:latest
